twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig', 'form/custom_layout.html.twig']
    globals:
        app_name: 'CulinaryConnect'

when@test:
    twig:
        strict_variables: true
